services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./bot/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/

  bot:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: "postgres://postgres:5432"
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: postgres
volumes:
  postgres_data:
