[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry]
# Core Devs
authors = ["kronifer", "ankith101.rar", "Da Cat Squid", "DawnOfMidnight", "Objectivix", "Dannynotsmart", "Aboo Minister"]
description = ""
name = "bot"
version = "0.1.0"

[tool.poetry.dependencies]
PyYAML = "^5.4.1"
datetime = "^4.3"
"discord.py" = "^1.7.1"
loguru = "^0.5.3"
python = "^3.8"
python-dotenv = "^0.17.0"
pytz = "^2021.1"
utils = "^1.0.1"

[tool.poetry.dev-dependencies]
black = "^24.3"
pytest = "^5.2"
taskipy = "^1.8.1"
flake8 = "^3.9.2"

[tool.taskipy.tasks]
start = "poetry run python -m bot"
lint = "poetry run flake8"
format = "poetry run black ."