name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2
        
      - name: Pull Changes and Restart Job
        run: |
          mkdir ~/.ssh && touch ~/.ssh/known_hosts && echo ${{ secrets.KNOWN_HOSTS }} >> ~/.ssh/known_hosts
          sshpass -p ${{ secrets.SSHPASS }} ssh -o "StrictHostKeyChecking no" -tt ${{ secrets.SSH }} -t "cd bot && git pull origin main && systemctl restart catbot"
